FROM node:22.15

WORKDIR /app
COPY package*.json ./
RUN npm install && npm install -g nodemon
COPY . .

EXPOSE 5173
CMD ["nodemon", "--watch", "package.json", "--exec", "npm install && npm run dev -- --host 0.0.0.0"]