version: '3.8'

services:
  frontend:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - prodnet
    depends_on:
      - backend

  backend:
    container_name: backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - prodnet
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - prodnet

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./db
      o: bind

networks:
  prodnet:
    driver: bridge
